baseURL: "https://gad-wissberg.netlify.app/"
languageCode: "en-us"
title: "Gad Wissberg"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Tutorials
      title: Tutorials
      url: /tutorials
      weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Gad Wissberg"
  description: I'm a software developer
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Gad Wissberg" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hello! I am"
    title: "Gad Wissberg"
    subtitle: "I'm a software developer"
    content: "I am deeply passionate about the programming and design fields, which have captivated me since I first started coding. Here you'll find tutorials on game development and additional information about me."
    image: /images/hero.svg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "CV"
      url: "/GadWissberg-CV.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/GadWissberg
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/gad-wissberg-781772150/

  recentPosts:
      path: "tutorials"
      count: 3
      title: Recent Tutorials
      enable: true
      disableFeaturedImage: false
      socialNetworks:
        github: https://github.com/GadWissberg
        linkedin: https://www.linkedin.com/in/gad-wissberg-781772150/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      I'm a highly skilled software developer with a passion for game and web development. With extensive experience in various technologies I thrive on solving complex problems and bringing innovative solutions to life. Currently, I'm working as a fullstack developer at Riskified. In my spare time, I channel my creativity into designing and developing my own mobile and desktop games, using cutting-edge tools and technologies to bring my visions to life.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Languages: Java, Kotlin, Scala, TypeScript, JS, SQL, HTML/CSS, Python"
        - "DB: PostgreSQL, Redis, Snowflake, MongoDB, Oracle"
        - "Web Development: Node.js, Kafka, AWS, Angular, Spring"
        - "OS: Windows, macOS, Linux"
        - "Game Development: Android, libGdx, openGL, Phaser, Blender, Photoshop, GameMaker"
        - "Other tools & services: Docker, Kubernetes, Terraform, Coralogix, Grafana"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Backend / Fullstack"
        company: "Riskified"
        companyUrl: "https://www.riskified.com/"
        date: "2022-present"
        info:
          enable: false
        featuredLink:
          enable: true
        content: |
          Full-Time Backend Development and Full-Stack at Riskified

          General Responsibilities
          	•	Lead development of key features and integrations
          Drive the full development lifecycle—including technical research, cross-team collaboration (Product, BI, Data, Integration Engineering), and system design. Take into account existing architecture, fault tolerance, scalability, and security best practices.
          	•	Multi-environment operations
          Work across staging, sandbox, and production environments. Manage logging, define alerts, and monitor dashboards for operational excellence.
          	•	Agile development
          Participate in refinement, planning, and epic breakdown processes. Implement features with tests in all scopes; add monitoring dashboards; and present completed work in demos.
          	•	On-call support
          Handle PagerDuty on-call rotations, collaborating with other teams to resolve incidents, debug issues, and guide peers through technical processes.
          	•	Quality initiatives
          Proactively introduced end-to-end (E2E) tests to cover critical domain flows, creating mock servers in staging and production environments and enhancing system reliability.
          	•	Recruitment
          Conduct technical interviews as part of the peer hiring process.

          ⸻

          Backend Developer — Connect Team
          	•	Third-party integrations
          Integrated with payment service providers (e.g., PayPal, Stripe), including API research, direct communication with such services, and applied business logic.
          	•	Strategic partnerships
          Extensive integration efforts with Justt to expand Riskified’s chargeback management capabilities.
          	•	Entity management
          Owned the lifecycle and logic of Riskified’s chargeback entity—processing incoming webhooks from payment providers and publishing relevant chargeback events.

          ⸻

          Backend / Full-Stack Developer — Chargeback Management System (CBMS)
          	•	Ethoca integration
          Led the integration of Ethoca’s (a Mastercard company) credit card transaction alerts, including partner communication, system design, and epic decomposition. Collaborated closely with Product, BI, and Design teams.
          	•	Web application development
          Delivered backend features for indexing and exposing CDC data to the CBMS React app. Built UI components to enable seamless user interaction with the processed data.

      - job: "Backend Developer"
        company: "Viaccess-Orca"
        companyUrl: "https://www.viaccess-orca.com"
        date: "2020-2022"
        info:
          enable: false
        featuredLink:
          enable: true
        content: |
          Java back-end development, using Spring Boot in a microservice architecture. Mostly object-oriented, but also
          developing in aspect-oriented. Development includes REST APIs, implementing features from the high-level
          design (including Swagger), through low-level design, implementation and writing tests (unit, component,
          integration and E2E) and also performing stress-tests (analyzing network, CPU, DB usage).

          Implementations include usage of MongoDB, taking into considerations major factors such as indexing, adding
          views in other microservices and optimized interactions with the DB. Also fair experience with OracleDB.
          Using and integrating Kafka for events distribution in a microservice environment. This includes analyzing and
          debugging Kafka integration with the product for an optimized performance.

          Handling support requests - Investigating product’s log files produced in the client’s machines in order to analyze,
          reproduce and fix bugs.

          Containerization - Working and deploying in Kubernetes for E2E tests, and viewing logs directly or Kibana. Using
          Docker and VM environments for component and stress tests. Also fair experience with AWS.

          Presenting demo sessions to relevant audiences for new features implemented by me and teammates.
          Leading integration for various features that require several microservices which are under the responsibility of
          other teams. These tasks require more communication with other teams, rather than concrete implementation.

          Development and deployment in Linux CentOS and Windows environments.
          Full teamwork in SAFe routine through each PI, mainly with developers, PMs and architects.
          Working with auxiliary development services such as Jira, Git, Gitlab and Jenkins.

      - job: "Software Developer - Student"
        company: "Algosec"
        companyUrl: "https://algosec.com"
        date: "2017-2020"
        info:
          enable: false
        featuredLink:
          enable: true
        content: |
          Part-time (60%-80%) software development at Algosec: Working as a FullStack (Mainly on the back-end) developer as part of Algosec Fireflow product team:
           - Java back-end development, in Spring Boot including development of REST API’s, networking-related services
           and controllers and unit/system tests (Mockito, JUnit). Also, refactored Perl legacy code to Java.
           - DB Development & management using PostgreSQL.
           - Investigating product’s log files produced in client’s machines in order to reproduce and fix bugs.
           - Fair experience with security devices of several brands such as Cisco, Fortinet, Juniper, CheckPoint and PaloAlto.
           - Fair frontend experience development in JS, AngularJS and Angular 9.
           - Full teamwork in Agile routine consisting of a variety of personnel such as QA, developers, UI & UX and PM’s.

      - job: "Android Developer"
        company: "Sociopal"
        date: "2014-2015"
        info:
          enable: false
          url: "https://example.com"
        content: |
          Client-side Java development in native environment for Android: Working with the elements of Android
          (LifeCycle, Activities, Intents, etc.), handling REST services and analyzing crash logs produced at user's devices.
          - Fair experience back-end development in PHP, with basic experience using MongoDB.
          - Teamwork in a development, staging and production environments with QA, developers, UI & UX and PM’s.
          - Experience with auxiliary development services and tools such as analytics, crash reporting and SVN.

      - job: "Taskforce"
        company: "Military - IDF"
        info:
          enable: false
        date: "2012-2014"
        content:
          "Military: Voluntary service at the intelligence force - highly classified operational unit at Givatayim.
          - Python development – Writing GUI's, scripts and automations.
          - Data communications – Working with the OSI model, managing networks and equipment configuring."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Holon Institute of Technology - HIT"
          url: "https://www.hit.ac.il/en"
        date: "2017 - 2020"
        GPA: "85"
        content: |-
          2012-2014: Data communications training at the IITC College within the military service.

          2007-2010: Full graduation at Campus KS Holon. CS class – 5 units at CS, physics, math and English.

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: ParaStrike
        content: A modern casual version of the retro game Paratrooper. Written in Java for Android, involves integration with Google Play Services to include in-app purchases, leader-boards and cloud saving.
        image: /images/parastrike.png
        featured:
          name: Google Play
          link: https://play.google.com/store/apps/details?id=com.gadarts.parashoot.android
        badges:
          - "Java"
          - "Android"
          - "libGdx"
        links:
          - icon: fab fa-github
            url: https://github.com/GadWissberg/parastrike

      - title: Shubutz
        content: A tiny Hebrew variation of the Hangman game. Designed both for mature and kids. Written in Kotlin for Android, involves integration with Google Play Services to include in-app purchases and leader-boards.
        image: /images/shubutz.png
        featured:
          name: Google Play
          link: https://play.google.com/store/apps/details?id=com.gadarts.shubutz&hl=en&gl=US
        badges:
          - "Kotlin"
          - "Android"
          - "libGdx"
        links:
          - icon: fab fa-github
            url: https://github.com/GadWissberg/words-bomb

      - title: Terror Effector
        content: A turn-based game for the desktop. Still in progress and available for download for testing. This is a much more detailed and complex project - All assets (except melodies) were made by me.
        image: /images/terror_effector.png
        badges:
          - "Java"
          - "Windows"
          - "Linux"
          - "libGdx"
        featured:
          name: itch.io
          link: https://gadarts.itch.io/terror-effector
        links:
          - icon: fab fa-github
            url: https://github.com/GadWissberg/industrial-game

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: Feel free to contact me!
    email: gadw17@gmail.com
    btnName: gadw17@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "tutorials"
      count: 3
      title: Recent Tutorials
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/GadWissberg
      linkedin: https://www.linkedin.com/in/gad-wissberg-781772150/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
